-- Inserir Resultados '2017-02-27', 'Club Sao Paulo'                                                                
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (33, 1, 251,  0 , 0); 
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (32, 1, 241,	0 , 1);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (11, 1, 230,	9 , 1);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (20, 1, 239,	0 , 1);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (14, 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (19, 1, 230,	24, 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (21, 1, 219,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (16, 1, 214,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (35, 1, 235,	42, 1);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (26, 1, 224,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (5 , 1, 0  ,  0 , 0); 
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (18, 1, 194,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (12, 1, 225,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (34, 1, 244,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (24, 1, 231,	0 , 1);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (36, 1, 226,	40, 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (4 , 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (37, 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (1 , 1, 175,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (10, 1, 227,	0 , 1);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (27, 1, 232,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (38, 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (40, 1, 246,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (25, 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (39, 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (41, 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (29, 1, 235, 12,  0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (17, 1, 230,	4 , 1);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (28, 1, 0  ,  0 , 0); 
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (22, 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (6 , 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (3 , 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (13, 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (7 , 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (30, 1, 226,	29, 1);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (2 , 1, 199,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (8 , 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (31, 1, 222,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (15, 1, 186,	0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (42, 1, 0  ,  0 , 0);	
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (9 , 1, 0  ,  0 , 0);	

-- Inserir Resultados '2017-04-16', 'DG Slot Racer'
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (33, 2, 270,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (32, 2, 254,	77, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (11, 2, 242,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (20, 2, 254,	1 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (14, 2, 269,	18, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (19, 2, 246,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (21, 2, 269,	74, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (16, 2, 247,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (35, 2, 258,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (26, 2, 235,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (5 , 2, 253,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (18, 2, 227,	71, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (12, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (34, 2, 71 ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (24, 2, 248,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (36, 2, 265,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (4 , 2, 226,	77, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (37, 2, 271,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (1 , 2, 201,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (10, 2, 241,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (27, 2, 252,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (38, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (40, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (25, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (39, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (41, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (29, 2, 71 ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (17, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (28, 2, 261,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (22, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (6 , 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (3 , 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (13, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (7 , 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (30, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (2 , 2, 200,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (8 , 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (31, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (15, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (42, 2, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (9 , 2, 0  ,	0 , 0);

-- Inserir Resultados '2017-05-14', 'Rato Raceway'
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (33, 3, 285,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (32, 3, 246,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (11, 3, 275,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (20, 3, 288,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (14, 3, 270,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (19, 3, 269,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (21, 3, 283,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (16, 3, 266,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (35, 3, 272,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (26, 3, 279,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (5 , 3, 262,	10, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (18, 3, 280,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (12, 3, 262,	47, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (34, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (24, 3, 265,	9 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (36, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (4 , 3, 227,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (37, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (1 , 3, 222,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (10, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (27, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (38, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (40, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (25, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (39, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (41, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (29, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (17, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (28, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (22, 3, 130,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (6 , 3, 265,	41, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (3 , 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (13, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (7 , 3, 262,	25, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (30, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (2 , 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (8 , 3, 254,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (31, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (15, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (42, 3, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (9 , 3, 0  ,	0 , 0);

-- Inserir Resultados '2017-07-16', 'Slot Club Jundiaí'
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (33, 4, 251,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (32, 4, 250,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (11, 4, 237,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (20, 4, 233,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (14, 4, 232,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (19, 4, 239,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (21, 4, 228,	42, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (16, 4, 241,	20, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (35, 4, 240,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (26, 4, 241,	24, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (5 , 4, 224,	10, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (18, 4, 227,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (12, 4, 226,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (34, 4, 224,	31, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (24, 4, 231,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (36, 4, 238,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (4 , 4, 228,	10, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (37, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (1 , 4, 220,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (10, 4, 211,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (27, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (38, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (40, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (25, 4, 243,	0 , 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (39, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (41, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (29, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (17, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (28, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (22, 4, 229,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (6 , 4, 204,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (3 , 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (13, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (7 , 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (30, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (2 , 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (8 , 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (31, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (15, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (42, 4, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (9 , 4, 0  ,	0 , 0);

-- Inserir Resultados '2017-09-17', 'Espaço Formula'
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (33, 5, 233,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (32, 5, 283,	0, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (11, 5, 297,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (20, 5, 119,	0, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (14, 5, 279,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (19, 5, 284,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (21, 5, 280,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (16, 5, 263,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (35, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (26, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (5 , 5, 285,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (18, 5, 260,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (12, 5, 278,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (34, 5, 258,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (24, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (36, 5, 125,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (4 , 5, 226,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (37, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (1 , 5, 282,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (10, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (27, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (38, 5, 311,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (40, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (25, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (39, 5, 290,	0, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (41, 5, 287,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (29, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (17, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (28, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (22, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (6 , 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (3 , 5, 265,	0, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (13, 5, 262,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (7 , 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (30, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (2 , 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (8 , 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (31, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (15, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (42, 5, 0  ,	0, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (9 , 5, 0  ,	0, 0);

-- Inserir Resultados '2017-11-26', 'Monza'
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (33, 6, 300,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (32, 6, 296,	67, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (11, 6, 289,	72, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (20, 6, 274,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (14, 6, 296,	18, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (19, 6, 294,	35, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (21, 6, 265,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (16, 6, 289,	27, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (35, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (26, 6, 273,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (5 , 6, 269,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (18, 6, 275,	28, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (12, 6, 280,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (34, 6, 277,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (24, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (36, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (4 , 6, 294,	49, 1);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (37, 6, 296,	55, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (1 , 6, 288,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (10, 6, 275,	64, 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (27, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (38, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (40, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (25, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (39, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (41, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (29, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (17, 6, 259,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (28, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (22, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (6 , 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (3 , 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (13, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (7 , 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (30, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (2 , 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (8 , 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (31, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (15, 6, 0  ,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (42, 6, 284,	0 , 0);
INSERT INTO resultado_etapa (piloto_categoria_id, etapa_id, voltas, zona, ponto_extra) VALUES (9 , 6, 238,	0 , 0);